cask "aerospace-edge" do # Generated by nightly workflow
  version :latest
  sha256 "7a487517bdef509e1b19f4525c1ce3f77a7af15b1d26ed365c7c5de9538cb7b5"

  url "https://github.com/ericreeves/AeroSpace/releases/download/nightly/AeroSpace-edge-2026-04-17.zip"
  name "AeroSpace"
  desc "AeroSpace is an i3-like tiling window manager for macOS (nightly edge build)"
  homepage "https://github.com/ericreeves/AeroSpace"
  conflicts_with cask: "aerospace", cask: "aerospace-dev"

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "xattr -d com.apple.quarantine #{staged_path}/AeroSpace-v0.0.0-SNAPSHOT/bin/aerospace"
    system "xattr -d com.apple.quarantine #{appdir}/AeroSpace.app"
  end

  app "AeroSpace-v0.0.0-SNAPSHOT/AeroSpace.app"
  binary "AeroSpace-v0.0.0-SNAPSHOT/bin/aerospace"

  binary "AeroSpace-v0.0.0-SNAPSHOT/shell-completion/zsh/_aerospace",
      target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_aerospace"
  binary "AeroSpace-v0.0.0-SNAPSHOT/shell-completion/bash/aerospace",
      target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/aerospace"
  binary "AeroSpace-v0.0.0-SNAPSHOT/shell-completion/fish/aerospace.fish",
      target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/aerospace.fish"

  Dir["#{staged_path}/AeroSpace-v0.0.0-SNAPSHOT/manpage/*"].each { |man| manpage man }
end
