cask "aerospace-edge" do # Generated by nightly workflow
  version :latest
  sha256 "9386ce14540d292f1dc57bfbe6abf9909c9a7e47af4297b95faf3178b36669d3"

  url "https://github.com/ericreeves/AeroSpace/releases/download/nightly/AeroSpace-edge-2026-07-25-7c38816e.zip"
  name "AeroSpace"
  desc "AeroSpace is an i3-like tiling window manager for macOS (nightly edge build)"
  homepage "https://github.com/ericreeves/AeroSpace"
  conflicts_with cask: ["aerospace", "aerospace-dev"]

  depends_on macos: :ventura # macOS 13+ (symbol form; string ">=" comparison deprecated in brew 5)

  postflight do
    system "xattr -d com.apple.quarantine #{staged_path}/AeroSpace-v0.0.0-SNAPSHOT/bin/aerospace"
    system "xattr -d com.apple.quarantine #{staged_path}/AeroSpace-v0.0.0-SNAPSHOT/bin/aerospace-helper"
    system "xattr -d com.apple.quarantine #{staged_path}/AeroSpace-v0.0.0-SNAPSHOT/bin/aero-notify"
    system "xattr -d com.apple.quarantine #{appdir}/AeroSpace.app"
  end

  app "AeroSpace-v0.0.0-SNAPSHOT/AeroSpace.app"
  binary "AeroSpace-v0.0.0-SNAPSHOT/bin/aerospace"
  binary "AeroSpace-v0.0.0-SNAPSHOT/bin/aerospace-helper"
  binary "AeroSpace-v0.0.0-SNAPSHOT/bin/aero-notify"

  binary "AeroSpace-v0.0.0-SNAPSHOT/shell-completion/zsh/_aerospace",
      target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_aerospace"
  binary "AeroSpace-v0.0.0-SNAPSHOT/shell-completion/bash/aerospace",
      target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/aerospace"
  binary "AeroSpace-v0.0.0-SNAPSHOT/shell-completion/fish/aerospace.fish",
      target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/aerospace.fish"

  Dir["#{staged_path}/AeroSpace-v0.0.0-SNAPSHOT/manpage/*"].each { |man| manpage man }
end
